version: '3.3'

services: 

    #PHP service
    app:
      container_name: app_con
      build: 
        context: .
        dockerfile: Dockerfile
      image: php:7.4
      tty: true
      environment: 
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www
      volumes: 
        - ./:/var/www
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks: 
        - app-network

    #NGINX service
    webserver:
      container_name: web_con
      image: nginx:alpine
      tty: true
      ports: 
        - '8080:80'
      volumes: 
        - ./:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      networks: 
        - app-network

    #MySql Service
    db:
      container_name: db_con
      image: mysql:latest
      tty: true
      ports: 
        - "3306:3306"
      environment: 
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: password
        SERVICE_NAME: mysql
        SERVICE_TAGS: dev
      volumes: 
        - dbdata:/var/lib/mysql
        - ./mysql/my.conf:/etc/mysql/my.conf
      networks: 
        - app-network

#Docker Networks
networks: 
  app-network:
    driver: bridge

#Volumes
volumes: 
  dbdata:
    driver: local
    